//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:2695/WebService/", ConfigurationName="ServiceReference1.OAWebServiceSoap")]
    public interface OAWebServiceSoap {
        
        // CODEGEN: 命名空间 http://localhost:2695/WebService/ 的元素名称 O_Schedule_code 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:2695/WebService/OASchedule", ReplyAction="*")]
        OAService.ServiceReference1.OAScheduleResponse OASchedule(OAService.ServiceReference1.OAScheduleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:2695/WebService/OASchedule", ReplyAction="*")]
        System.Threading.Tasks.Task<OAService.ServiceReference1.OAScheduleResponse> OAScheduleAsync(OAService.ServiceReference1.OAScheduleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAScheduleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OASchedule", Namespace="http://localhost:2695/WebService/", Order=0)]
        public OAService.ServiceReference1.OAScheduleRequestBody Body;
        
        public OAScheduleRequest() {
        }
        
        public OAScheduleRequest(OAService.ServiceReference1.OAScheduleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:2695/WebService/")]
    public partial class OAScheduleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string O_Schedule_code;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string C_userinfo_code;
        
        public OAScheduleRequestBody() {
        }
        
        public OAScheduleRequestBody(string O_Schedule_code, string C_userinfo_code) {
            this.O_Schedule_code = O_Schedule_code;
            this.C_userinfo_code = C_userinfo_code;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OAScheduleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OAScheduleResponse", Namespace="http://localhost:2695/WebService/", Order=0)]
        public OAService.ServiceReference1.OAScheduleResponseBody Body;
        
        public OAScheduleResponse() {
        }
        
        public OAScheduleResponse(OAService.ServiceReference1.OAScheduleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://localhost:2695/WebService/")]
    public partial class OAScheduleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OAScheduleResult;
        
        public OAScheduleResponseBody() {
        }
        
        public OAScheduleResponseBody(string OAScheduleResult) {
            this.OAScheduleResult = OAScheduleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OAWebServiceSoapChannel : OAService.ServiceReference1.OAWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OAWebServiceSoapClient : System.ServiceModel.ClientBase<OAService.ServiceReference1.OAWebServiceSoap>, OAService.ServiceReference1.OAWebServiceSoap {
        
        public OAWebServiceSoapClient() {
        }
        
        public OAWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OAWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OAWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OAService.ServiceReference1.OAScheduleResponse OAService.ServiceReference1.OAWebServiceSoap.OASchedule(OAService.ServiceReference1.OAScheduleRequest request) {
            return base.Channel.OASchedule(request);
        }
        
        public string OASchedule(string O_Schedule_code, string C_userinfo_code) {
            OAService.ServiceReference1.OAScheduleRequest inValue = new OAService.ServiceReference1.OAScheduleRequest();
            inValue.Body = new OAService.ServiceReference1.OAScheduleRequestBody();
            inValue.Body.O_Schedule_code = O_Schedule_code;
            inValue.Body.C_userinfo_code = C_userinfo_code;
            OAService.ServiceReference1.OAScheduleResponse retVal = ((OAService.ServiceReference1.OAWebServiceSoap)(this)).OASchedule(inValue);
            return retVal.Body.OAScheduleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OAService.ServiceReference1.OAScheduleResponse> OAService.ServiceReference1.OAWebServiceSoap.OAScheduleAsync(OAService.ServiceReference1.OAScheduleRequest request) {
            return base.Channel.OAScheduleAsync(request);
        }
        
        public System.Threading.Tasks.Task<OAService.ServiceReference1.OAScheduleResponse> OAScheduleAsync(string O_Schedule_code, string C_userinfo_code) {
            OAService.ServiceReference1.OAScheduleRequest inValue = new OAService.ServiceReference1.OAScheduleRequest();
            inValue.Body = new OAService.ServiceReference1.OAScheduleRequestBody();
            inValue.Body.O_Schedule_code = O_Schedule_code;
            inValue.Body.C_userinfo_code = C_userinfo_code;
            return ((OAService.ServiceReference1.OAWebServiceSoap)(this)).OAScheduleAsync(inValue);
        }
    }
}
